# ----Training parameters --------------------------------
n_epoch: 5
layers: 3
channels: 1
features: 192

n_workers: 6
scheduler_mode: min
scheduler_patience: 1
model_name: subnet
loss_function: 'L2'
alpha_loss: [0.01]

trainset: 'val'
valset: 'val'
normalize: True
clip: False
sigma_range: [10, 15]
device: 'cuda:0'
output_mode: "image"

# ----Dataset parameters --------------------------------
dataset_stride: 9
batch_size: 8

# Adam Optimizer
alpha_adam: 0.01
beta1_adam: 0.9
beta2_adam: 0.999
epsilon_adam: 1.0E-8
